export const ALL_DOCTOR_REQUEST = "ALL_DOCTOR_REQUEST";
export const ALL_DOCTOR_SUCCESS = "ALL_DOCTOR_SUCCESS";
export const ALL_DOCTOR_FAIL = "ALL_DOCTOR_FAIL";

export const ADMIN_DOCTOR_REQUEST = "ADMIN_DOCTOR_REQUEST";
export const ADMIN_DOCTOR_SUCCESS = "ADMIN_DOCTOR_SUCCESS";
export const ADMIN_DOCTOR_FAIL = "ADMIN_DOCTOR_FAIL";

export const NEW_DOCTOR_REQUEST = "NEW_DOCTOR_REQUEST";
export const NEW_DOCTOR_SUCCESS = "NEW_DOCTOR_SUCCESS";
export const NEW_DOCTOR_RESET = "NEW_DOCTOR_RESET";
export const NEW_DOCTOR_FAIL = "NEW_DOCTOR_FAIL";

export const UPDATE_DOCTOR_REQUEST = "UPDATE_DOCTOR_REQUEST";
export const UPDATE_DOCTOR_SUCCESS = "UPDATE_DOCTOR_SUCCESS";
export const UPDATE_DOCTOR_RESET = "UPDATE_DOCTOR_RESET";
export const UPDATE_DOCTOR_FAIL = "UPDATE_DOCTOR_FAIL";

export const DELETE_DOCTOR_REQUEST = "DELETE_DOCTOR_REQUEST";
export const DELETE_DOCTOR_SUCCESS = "DELETE_DOCTOR_SUCCESS";
export const DELETE_DOCTOR_RESET = "DELETE_DOCTOR_RESET";
export const DELETE_DOCTOR_FAIL = "DELETE_DOCTOR_FAIL";

export const DOCTOR_DETAILS_REQUEST = "DOCTOR_DETAILS_REQUEST";
export const DOCTOR_DETAILS_SUCCESS = "DOCTOR_DETAILS_SUCCESS";
export const DOCTOR_DETAILS_FAIL = "DOCTOR_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
